"""Record application-owned stdio bytes; never construct or interpret MCP messages."""

from contextlib import ExitStack
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import select
import signal
import subprocess
import sys
import tempfile
import threading
import time


TERMINATION_GRACE_SECONDS = 2
KILL_WAIT_SECONDS = 2
RELAY_DRAIN_SECONDS = 1
IO_POLL_SECONDS = 0.05


def timestamp() -> str:
    """Use UTC for correlation across application restarts."""
    return datetime.now(timezone.utc).isoformat()


def write_all(destination: int, data: bytes, stop=None) -> bool:
    """Preserve partial writes; cancellable nonblocking pipes cannot hold up shutdown."""
    remaining = memoryview(data)
    while remaining:
        if stop is not None:
            if stop.is_set():
                return False
            if not select.select([], [destination], [], IO_POLL_SECONDS)[1]:
                continue
        try:
            written = os.write(destination, remaining)
        except BlockingIOError:
            continue
        if written == 0:
            raise OSError("zero-length pipe write")
        remaining = remaining[written:]
    return True


def write_metadata(path: Path, metadata: dict) -> None:
    """Readers see a complete startup or completion record."""
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(metadata, indent=2) + "\n")
    temporary.replace(path)


def run(config_path: Path) -> int:
    """Launch the frozen candidate with an explicitly replaced environment."""
    config = json.loads(config_path.read_text())
    argv = config["argv"]
    environment = config["env"]
    if not isinstance(argv, list) or not argv or not all(isinstance(v, str) for v in argv):
        raise ValueError("argv must be a nonempty list of strings")
    if not isinstance(environment, dict) or not all(
        isinstance(k, str) and isinstance(v, str) for k, v in environment.items()
    ):
        raise ValueError("env must contain string keys and values")
    binary = Path(argv[0])
    if not binary.is_absolute():
        raise ValueError("candidate executable must be absolute")
    binary_digest = hashlib.sha256(binary.read_bytes()).hexdigest()
    if binary_digest != config["binary_sha256"]:
        raise ValueError("binary hash mismatch; prepare a new candidate run")
    root = Path(config["cwd"]).resolve(strict=True)
    transcripts = Path(config["transcript_directory"]).resolve()
    if not transcripts.is_relative_to(root):
        raise ValueError("transcripts must remain inside the disposable run")
    transcripts.mkdir(parents=True, exist_ok=True)
    session = Path(tempfile.mkdtemp(prefix="session-", dir=transcripts))
    errors: list[str] = []
    signals: list[int] = []
    metadata = {
        "format": "bif-application-owned-stdio-capture-v1",
        "started_at": timestamp(), "ended_at": None,
        "launcher_pid": os.getpid(), "server_pid": None, "exit_code": None,
        "argv": argv, "cwd": str(root), "environment": environment,
        "binary_sha256": binary_digest,
        "launcher_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "launch_config_sha256": hashlib.sha256(config_path.read_bytes()).hexdigest(),
        "python": sys.version, "relay_errors": errors, "received_signals": signals,
        "disclosure": "Raw bytes from the configured application; no client requests are generated by this launcher.",
    }
    child = subprocess.Popen(
        argv, cwd=root, env=environment,
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        bufsize=0,
    )
    metadata["server_pid"] = child.pid
    shutdown = threading.Event()
    input_stop = threading.Event()
    output_stop = threading.Event()
    stdout_done = threading.Event()

    def forward_signal(number, _frame):
        signals.append(number)
        shutdown.set()
        if child.poll() is None:
            child.send_signal(number)

    handlers = {number: signal.signal(number, forward_signal) for number in (signal.SIGTERM, signal.SIGINT)}

    def relay(source: int, destination: int, capture, label: str, stop, close_input=False):
        """Capture opaque chunks and forward them without framing or buffering lines."""
        try:
            while not stop.is_set():
                if not select.select([source], [], [], IO_POLL_SECONDS)[0]:
                    continue
                try:
                    data = os.read(source, 65536)
                except BlockingIOError:
                    continue
                if not data:
                    break
                write_all(capture.fileno(), data)
                if not write_all(destination, data, stop):
                    break
        except (OSError, ValueError) as error:
            errors.append(f"{label}: {error}")
            shutdown.set()
            if child.poll() is None:
                child.terminate()
        finally:
            if close_input:
                child.stdin.close()
            if label == "stdout":
                stdout_done.set()

    try:
        write_metadata(session / "session.json", metadata)
        with ExitStack() as stack:
            incoming = stack.enter_context((session / "client-to-server.bin").open("xb", buffering=0))
            outgoing = stack.enter_context((session / "server-to-client.bin").open("xb", buffering=0))
            diagnostics = stack.enter_context((session / "server-stderr.bin").open("xb", buffering=0))
            # Restore host descriptors only after every relay has stopped using them.
            for descriptor in (0, 1, 2):
                stack.callback(os.set_blocking, descriptor, os.get_blocking(descriptor))
                os.set_blocking(descriptor, False)
            for stream in (child.stdin, child.stdout, child.stderr):
                os.set_blocking(stream.fileno(), False)
            input_thread = threading.Thread(
                target=relay, args=(0, child.stdin.fileno(), incoming, "stdin", input_stop, True),
            )
            output_thread = threading.Thread(
                target=relay, args=(child.stdout.fileno(), 1, outgoing, "stdout", output_stop),
            )
            error_thread = threading.Thread(
                target=relay, args=(child.stderr.fileno(), 2, diagnostics, "stderr", output_stop),
            )
            threads = []
            try:
                for thread in (input_thread, output_thread, error_thread):
                    thread.start()
                    threads.append(thread)
                termination_deadline = None
                eof_deadline = None
                # Child supervision must never depend on host or child pipe progress.
                while child.poll() is None:
                    now = time.monotonic()
                    if shutdown.is_set():
                        if termination_deadline is None:
                            termination_deadline = now + TERMINATION_GRACE_SECONDS
                        if now >= termination_deadline:
                            child.kill()
                            child.wait(timeout=KILL_WAIT_SECONDS)
                            break
                    elif stdout_done.is_set():
                        if eof_deadline is None:
                            eof_deadline = now + 5
                        if now >= eof_deadline:
                            child.terminate()
                            shutdown.set()
                    time.sleep(IO_POLL_SECONDS)
            finally:
                try:
                    if child.poll() is None:
                        shutdown.set()
                        child.kill()
                        child.wait(timeout=KILL_WAIT_SECONDS)
                finally:
                    input_stop.set()
                    # Normal EOF remains lossless even if the host is a slow reader.
                    # Only requested/failed shutdown bounds the final output drain.
                    drain_deadline = None
                    outputs = [(thread, label) for thread, label in
                               ((output_thread, "stdout"), (error_thread, "stderr"))
                               if thread in threads]
                    while any(thread.is_alive() for thread, _ in outputs):
                        if shutdown.is_set():
                            if drain_deadline is None:
                                drain_deadline = time.monotonic() + RELAY_DRAIN_SECONDS
                            if time.monotonic() >= drain_deadline:
                                for thread, label in outputs:
                                    if thread.is_alive():
                                        errors.append(f"{label} relay did not drain before shutdown")
                                break
                        for thread, _ in outputs:
                            thread.join(timeout=IO_POLL_SECONDS)
                    output_stop.set()
                    for thread in threads:
                        thread.join()
    finally:
        try:
            if child.poll() is None:
                child.kill()
                child.wait(timeout=KILL_WAIT_SECONDS)
        finally:
            metadata["ended_at"] = timestamp()
            metadata["exit_code"] = child.returncode
            try:
                write_metadata(session / "session.json", metadata)
            finally:
                for number, handler in handlers.items():
                    signal.signal(number, handler)
                for stream in (child.stdin, child.stdout, child.stderr):
                    stream.close()
    if errors:
        return 1
    return child.returncode if child.returncode >= 0 else 128 - child.returncode


if __name__ == "__main__":
    try:
        if len(sys.argv) != 2:
            raise ValueError("usage: stdio_tap.py /absolute/path/to/launch.json")
        sys.exit(run(Path(sys.argv[1]).resolve(strict=True)))
    except (OSError, ValueError, KeyError) as error:
        print(f"stdio_tap: {error}", file=sys.stderr)
        sys.exit(1)
