"""Record application-owned stdio bytes; never construct or interpret MCP messages."""

from contextlib import ExitStack
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import signal
import subprocess
import sys
import tempfile
import threading


def timestamp() -> str:
    """Use UTC for correlation across application restarts."""
    return datetime.now(timezone.utc).isoformat()


def write_all(destination: int, data: bytes) -> None:
    """Pipe writes may be partial; preserve every byte and its order."""
    remaining = memoryview(data)
    while remaining:
        written = os.write(destination, remaining)
        if written == 0:
            raise OSError("zero-length pipe write")
        remaining = remaining[written:]


def write_metadata(path: Path, metadata: dict) -> None:
    """Readers see a complete startup or completion record."""
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(metadata, indent=2) + "\n")
    temporary.replace(path)


def run(config_path: Path) -> int:
    """Launch the frozen candidate with an explicitly replaced environment."""
    config = json.loads(config_path.read_text())
    argv = config["argv"]
    environment = config["env"]
    if not isinstance(argv, list) or not argv or not all(isinstance(v, str) for v in argv):
        raise ValueError("argv must be a nonempty list of strings")
    if not isinstance(environment, dict) or not all(
        isinstance(k, str) and isinstance(v, str) for k, v in environment.items()
    ):
        raise ValueError("env must contain string keys and values")
    binary = Path(argv[0])
    if not binary.is_absolute():
        raise ValueError("candidate executable must be absolute")
    binary_digest = hashlib.sha256(binary.read_bytes()).hexdigest()
    if binary_digest != config["binary_sha256"]:
        raise ValueError("binary hash mismatch; prepare a new candidate run")
    root = Path(config["cwd"]).resolve(strict=True)
    transcripts = Path(config["transcript_directory"]).resolve()
    if not transcripts.is_relative_to(root):
        raise ValueError("transcripts must remain inside the disposable run")
    transcripts.mkdir(parents=True, exist_ok=True)
    session = Path(tempfile.mkdtemp(prefix="session-", dir=transcripts))
    errors: list[str] = []
    signals: list[int] = []
    metadata = {
        "format": "bif-application-owned-stdio-capture-v1",
        "started_at": timestamp(), "ended_at": None,
        "launcher_pid": os.getpid(), "server_pid": None, "exit_code": None,
        "argv": argv, "cwd": str(root), "environment": environment,
        "binary_sha256": binary_digest,
        "launcher_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "launch_config_sha256": hashlib.sha256(config_path.read_bytes()).hexdigest(),
        "python": sys.version, "relay_errors": errors, "received_signals": signals,
        "disclosure": "Raw bytes from the configured application; no client requests are generated by this launcher.",
    }
    child = subprocess.Popen(
        argv, cwd=root, env=environment,
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        bufsize=0,
    )
    metadata["server_pid"] = child.pid
    write_metadata(session / "session.json", metadata)

    def forward_signal(number, _frame):
        signals.append(number)
        if child.poll() is None:
            child.send_signal(number)

    handlers = {number: signal.signal(number, forward_signal) for number in (signal.SIGTERM, signal.SIGINT)}

    def relay(source: int, destination: int, capture, label: str, close_input=False):
        """Capture opaque chunks and forward them without framing or buffering lines."""
        try:
            while True:
                data = os.read(source, 65536)
                if not data:
                    break
                write_all(capture.fileno(), data)
                write_all(destination, data)
        except (OSError, ValueError) as error:
            errors.append(f"{label}: {error}")
            if child.poll() is None:
                child.terminate()
        finally:
            if close_input:
                child.stdin.close()

    try:
        with ExitStack() as stack:
            incoming = stack.enter_context((session / "client-to-server.bin").open("xb", buffering=0))
            outgoing = stack.enter_context((session / "server-to-client.bin").open("xb", buffering=0))
            diagnostics = stack.enter_context((session / "server-stderr.bin").open("xb", buffering=0))
            input_thread = threading.Thread(
                target=relay, args=(0, child.stdin.fileno(), incoming, "stdin", True), daemon=True,
            )
            error_thread = threading.Thread(
                target=relay, args=(child.stderr.fileno(), 2, diagnostics, "stderr"), daemon=True,
            )
            input_thread.start()
            error_thread.start()
            relay(child.stdout.fileno(), 1, outgoing, "stdout")
            try:
                child.wait(timeout=5)
            except subprocess.TimeoutExpired:
                child.terminate()
                child.wait(timeout=5)
            error_thread.join(timeout=5)
            if error_thread.is_alive():
                errors.append("stderr relay did not finish")
    finally:
        if child.poll() is None:
            child.kill()
            child.wait(timeout=5)
        metadata["ended_at"] = timestamp()
        metadata["exit_code"] = child.returncode
        write_metadata(session / "session.json", metadata)
        for number, handler in handlers.items():
            signal.signal(number, handler)
        for stream in (child.stdin, child.stdout, child.stderr):
            stream.close()
    if errors:
        return 1
    return child.returncode if child.returncode >= 0 else 128 - child.returncode


if __name__ == "__main__":
    try:
        if len(sys.argv) != 2:
            raise ValueError("usage: stdio_tap.py /absolute/path/to/launch.json")
        sys.exit(run(Path(sys.argv[1]).resolve(strict=True)))
    except (OSError, ValueError, KeyError) as error:
        print(f"stdio_tap: {error}", file=sys.stderr)
        sys.exit(1)
